name: iChaiwut
markdown: redcarpet
highlighter: true
permalink: pretty
gems: [jekyll-paginate]
paginate: 10
paginate_path: "/blog/page:num/"
url: https://chaiwut.me/
imageurl: https://ichaiwut.github.io/img/
comments: true

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics :
  provider : google
  google :
      tracking_id : 'UA-87576538-1'
