name: iChaiwut
markdown: redcarpet
highlighter: true
permalink: /:year/:month/:day/:title
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
url: http://ting.in.th
imageurl: http://ichaiwut.github.io/img/
comments: true

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics :
  provider : google
  google :
      tracking_id : 'UA-65871198-1'
